export const channelActionType ={
    SET_USER_CHANNEL: 'SET_USER_CHANNEL',
    SET_CURRENT_CHANNEL: 'SET_CURRENT_CHANNEL',
    PRIVATE_CHANNEL : 'PRIVATE_CHANNEL',
    SET_USERS_POST: 'SET_USERS_POST',
    SET_COLOR:'SET_COLOR',

}